"""
Signal — canonical shared model for trading signals.

This is the SINGLE source of truth for the Signal type.
All services (strategy_engine, risk_engine, execution_engine) import from here.

No service should define or redefine Signal locally — doing so would mean a
schema change in one service silently breaks another.

Signal flow: strategy_engine  ──▶  risk_engine  ──▶  execution_engine
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Optional

from shared.utils.helpers import generate_correlation_id, utc_now


class Direction(str, Enum):
    """Trade direction."""
    BUY = "BUY"
    SELL = "SELL"


class SignalStatus(str, Enum):
    """Signal lifecycle status."""
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


@dataclass
class Signal:
    """
    A trading signal generated by a strategy.

    Signals flow: Strategy Engine -> Risk Engine -> Execution Engine.

    ``signal_id`` provides idempotency — the same signal delivered twice produces
    only one order (enforced by DynamoDB conditional write in the execution engine).

    ``generated_at`` records when the strategy produced the signal. The risk engine
    uses this to reject signals whose age exceeds ``max_signal_age_seconds``, preventing
    stale signals from executing after a restart or processing queue backup.

    Attributes:
        signal_id:     Unique identifier — used for deduplication.
        symbol:        Trading symbol (e.g., "RELIANCE", "AAPL").
        market:        Market identifier ("NSE" or "US").
        direction:     BUY or SELL.
        quantity:      Number of shares/units.
        confidence:    Strategy confidence score (0.0–1.0).
        strategy_name: Name of the strategy that generated this signal.
        generated_at:  UTC timestamp when the signal was created by the strategy.
                       Used by the risk engine for staleness validation.
        timestamp:     Alias for generated_at — preserved for backward compat.
        status:        Current lifecycle status.
        price_at_signal: Market price when signal was generated.
        stop_loss:     Optional stop-loss price.
        take_profit:   Optional take-profit price.
        paper_trade:   If True, execution engine routes to paper endpoint —
                       never calls live broker.  All strategies start with
                       paper_trade=True until 5-day paper validation passes.
                       Schema version stays 3.0 (additive, safe default False).
        metadata:      Additional strategy-specific metadata.
    """

    symbol: str
    market: str
    direction: Direction
    quantity: int
    confidence: float
    strategy_name: str
    signal_id: str = field(default_factory=generate_correlation_id)
    generated_at: datetime = field(default_factory=utc_now)
    status: SignalStatus = SignalStatus.PENDING
    price_at_signal: float = 0.0
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    paper_trade: bool = False  # Phase 3 — paper_trade pipeline (ADR-013)
    metadata: dict[str, Any] = field(default_factory=dict)

    # ── Backward compatibility ────────────────────────────────────────────────
    # ``timestamp`` was the original field name.  New code must use
    # ``generated_at``.  Kept as a property so existing serialization round-trips
    # (``from_dict`` reads "timestamp" key) continue to work during migration.
    @property
    def timestamp(self) -> datetime:
        """Alias for generated_at — backward compat only."""
        return self.generated_at

    def to_dict(self) -> dict[str, Any]:
        """Serialize the signal to a dict for JSON transport."""
        return {
            "signal_id": self.signal_id,
            "symbol": self.symbol,
            "market": self.market,
            "direction": self.direction.value,
            "quantity": self.quantity,
            "confidence": self.confidence,
            "strategy_name": self.strategy_name,
            # Write both keys so consumers on either field name work
            "generated_at": self.generated_at.isoformat(),
            "timestamp": self.generated_at.isoformat(),
            "status": self.status.value,
            "price_at_signal": self.price_at_signal,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "paper_trade": self.paper_trade,  # Phase 3 — additive field, default False
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Signal:
        """Deserialize a signal from a dict.

        Accepts both ``generated_at`` and the legacy ``timestamp`` key so that
        messages already in-flight when this change is deployed still parse
        correctly.
        """
        # Prefer generated_at; fall back to legacy timestamp key
        raw_ts = data.get("generated_at") or data.get("timestamp")
        generated_at = datetime.fromisoformat(raw_ts) if raw_ts else utc_now()

        return cls(
            signal_id=data["signal_id"],
            symbol=data["symbol"],
            market=data["market"],
            direction=Direction(data["direction"]),
            quantity=int(data["quantity"]),
            confidence=float(data["confidence"]),
            strategy_name=data["strategy_name"],
            generated_at=generated_at,
            status=SignalStatus(data.get("status", "PENDING")),
            price_at_signal=float(data.get("price_at_signal", 0.0)),
            stop_loss=data.get("stop_loss"),
            take_profit=data.get("take_profit"),
            paper_trade=bool(data.get("paper_trade", False)),  # Phase 3 — safe default
            metadata=data.get("metadata", {}),
        )
