"""
Signal dataclass — the output of a strategy engine.

A Signal represents a trading intention that must be validated by the Risk Engine
before being converted to an Order for execution.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Optional

from shared.utils.helpers import generate_correlation_id, utc_now


class Direction(str, Enum):
    """Trade direction."""
    BUY = "BUY"
    SELL = "SELL"


class SignalStatus(str, Enum):
    """Signal lifecycle status."""
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


@dataclass
class Signal:
    """
    A trading signal generated by a strategy.

    Signals flow: Strategy Engine -> Risk Engine -> Execution Engine.
    The signal_id is used for idempotency — duplicate signals with the same ID
    are rejected by the risk engine.

    Attributes:
        signal_id: Unique identifier for idempotency.
        symbol: Trading symbol (e.g., "RELIANCE", "AAPL").
        market: Market identifier (e.g., "NSE", "US").
        direction: BUY or SELL.
        quantity: Number of shares/units.
        confidence: Strategy confidence score (0.0 to 1.0).
        strategy_name: Name of the strategy that generated this signal.
        timestamp: When the signal was generated.
        status: Current lifecycle status.
        price_at_signal: Market price when signal was generated.
        metadata: Additional strategy-specific metadata.
    """

    symbol: str
    market: str
    direction: Direction
    quantity: int
    confidence: float
    strategy_name: str
    signal_id: str = field(default_factory=generate_correlation_id)
    timestamp: datetime = field(default_factory=utc_now)
    status: SignalStatus = SignalStatus.PENDING
    price_at_signal: float = 0.0
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Serialize the signal to a dictionary for SQS/JSON transport."""
        return {
            "signal_id": self.signal_id,
            "symbol": self.symbol,
            "market": self.market,
            "direction": self.direction.value,
            "quantity": self.quantity,
            "confidence": self.confidence,
            "strategy_name": self.strategy_name,
            "timestamp": self.timestamp.isoformat(),
            "status": self.status.value,
            "price_at_signal": self.price_at_signal,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Signal:
        """Deserialize a signal from a dictionary."""
        return cls(
            signal_id=data["signal_id"],
            symbol=data["symbol"],
            market=data["market"],
            direction=Direction(data["direction"]),
            quantity=int(data["quantity"]),
            confidence=float(data["confidence"]),
            strategy_name=data["strategy_name"],
            timestamp=datetime.fromisoformat(data["timestamp"]),
            status=SignalStatus(data.get("status", "PENDING")),
            price_at_signal=float(data.get("price_at_signal", 0.0)),
            stop_loss=data.get("stop_loss"),
            take_profit=data.get("take_profit"),
            metadata=data.get("metadata", {}),
        )
